### ISSUE TITLE
❓  Question - About plugin update  development

### ISSUE THREAD

**Issue by NoNameTrademark** [JackCeparou/Troubadour#2]
Hi,

Are there any new features being developed or is the project just being updated?
Is there a private fork, discord or any other platform where we can participate?

Thank you for your work

**Comment by JackCeparou** [comment]
Hi,

- new features: no
- will be updated: 
  - this repository: no, 'cause not playing anymore
  - framework: no idea, they just asked to use/include my plugins.
- other platform(s): none that I know

Feel free to fork this repository or even copy/paste part of it.

**Comment by NoNameTrademark** [comment]
Is there a way to add section titles or other text and spacing into the interface? This quickly becomes illegible.
Maybe by adding some Resource with no properties ?

<a href="https://ibb.co/fvgkVRd"><img src="https://i.ibb.co/fvgkVRd/werqaw423weraq34tawef.png" alt="werqaw423weraq34tawef" border="0"></a>

**Comment by JackCeparou** [comment]
these forms are part of the framework and not configurable (you can only define them with plugins/features/resources)
