### ISSUE TITLE
Gizmo_State

### ISSUE THREAD

**Issue by NoNameTrademark** [JackCeparou/Troubadour#3]
I would like to delete the chests from the map when they are open. There is a way to set if Gizmo_State = 1
Value that a get in the logs actor.csv

****	****	****	Bandit_Chest_Rare_01_Dyn	None	****	Chest	****	****	****	None	0	0
		Level	-	1	1E-45
		Hitpoints_Max_Total	-	****	****
		Hitpoints_Max	-	****	****
		Hitpoints_Cur	-	****	****
		TeamID	-	1	1E-45
		Gizmo_State	-	1	1E-45

**Comment by JackCeparou** [comment]
It's not possible for the plugins to read attributes not exposed by the framework.
And afaik the GizmoState is not exposed.

Btw, something probably broke because the opened chests were filtered by the framework with official releases.

**Comment by NoNameTrademark** [comment]
Do you have a list of objects and properties supported in the latest version of the framework before the project was abandoned? Or a script to list them directly in a log. 

If it is negative on both points, you can close this issue.

Thanks you for your time.

**Comment by JackCeparou** [comment]
There is also a 3rd option.

You can decompile T4.GameEnum.dll & T4.Plugins.dll, they are not obfuscated, everything is there.
They basically contains what was distributed in the `/interfaces` folder.

Some tools to do it:
- [dotPeek](https://www.jetbrains.com/decompiler/download/#section=web-installer)
- [JustDecompile](https://www.telerik.com/products/decompiler.aspx)
- [dnSpy](https://github.com/dnSpy/dnSpy)
